// 将本地查询投影到已冻结的静态证据，公网页面无需运行 Python 服务。
let relationCache;
async function evidenceFetch(path) {
 const u=new URL(path,location.href);
 if(u.pathname==='/context/projection.json')return fetch('./projection.json');
 if(u.pathname==='/context/icfg')return fetch('./calls/'+encodeURIComponent(u.searchParams.get('entity'))+'.json');
 if(u.pathname==='/context/relations'){
  const all=await (relationCache??=fetch('./relations.json').then(r=>r.json()));
  const ids=new Set(u.searchParams.get('entities').split(','));
  const relations=all.filter(r=>ids.has(r.from)&&ids.has(r.to));
  return new Response(JSON.stringify({relations,call_count:relations.reduce((n,r)=>n+r.calls.length,0)}),{headers:{'Content-Type':'application/json'}});
 }
 if(u.pathname==='/__source'){
  const file=u.searchParams.get('file');
  if(file.split('/').includes('..'))return new Response('外部依赖源码不在固定 Codex 源码交付中。');
  const r=await fetch('./sources/'+file+'.json');
  if(!r.ok)return new Response('该源码文件未包含在本次静态交付中。',{status:404});
  const lines=await r.json(),a=Number(u.searchParams.get('start')),b=Number(u.searchParams.get('end'));
  if(a<1||b<a||b>lines.length)return new Response('源码行号超出已冻结文件范围。',{status:404});
  return new Response(lines.slice(a-1,b).map((line,i)=>String(a+i).padStart(5)+' '+line).join('\n'));
 }
 throw new Error('未支持的证据请求：'+u.pathname);
}
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data,flow,view='flow',selected=null;const kinds={source_sequence:'源码顺序',conditional:'条件分支',loop:'续步／循环',queue_handoff:'跨任务消息交接',async_handoff:'异步结果消费',interface_handoff:'接口交接',static_dependency:'静态依赖',stage_boundary:'阶段交接',task_boundary:'任务边界',shared_state:'共享状态'};
const entities=n=>n.members.map(k=>data.entities[k]);
function sourceButton(id){const e=data.evidence[id];return `<button data-source="${esc(id)}">看源码 ${esc(e.file)}:${e.start}–${e.end}</button>`}
function memberHtml(e){return `<div class="entity"><h4>${esc(e.name)}</h4><div class="code-path">${esc(e.canonical_path)}</div><p><b>函数做什么：</b>${esc(e.function_role)}</p><p class="muted">模块职责：${esc(e.role||'见源码／已有分析')}</p><div class="code-path">crate ${esc(e.crate)} · ${esc(e.module)}<br>${esc(e.file)}:${e.start}–${e.end}</div><span class="tag">${e.body_keys.length} 个匹配 Body</span><span class="tag">${esc(({source_span_and_identity_bridge:'已匹配源码与原生 Body',source_only_no_body_match:'仅源码；未匹配 Body',ambiguous_native_span:'身份有歧义'})[e.identity_status]||e.identity_status)}</span><br><button data-function="${esc(e.id)}">展开源码与原生调用</button></div>`}
function selectNode(id){const n=flow.nodes.find(n=>n.id===id);selected=n; $('detail').hidden=false;$('detail').className='detail-box';$('detail').innerHTML=`<div class="details-head"><h3>${esc(n.title)}</h3><button data-close>收起详情</button></div><p>${esc(n.description)}</p><p><b>交给下一步：</b>${esc(n.output)}</p><div>${n.questions.map(q=>`<button data-question="${q}">${q}</button>`).join(' ')}</div><div class="members">${entities(n).map(memberHtml).join('')||'<p>该位置暂未唯一匹配源码函数，保留源码锚点；不伪造函数身份。</p>'}</div>${n.evidence.map(sourceButton).join(' ')}<div id="source-pane"></div>`;$('detail').scrollIntoView({behavior:'smooth',block:'nearest'});bind();}
async function showFunction(id){const e=data.entities[id];const calls=await evidenceFetch('/context/icfg?entity='+encodeURIComponent(id)).then(r=>r.json());$('detail').hidden=false;$('detail').className='detail-box';$('detail').innerHTML=`<div class="details-head"><h3>${esc(e.name)}</h3><button data-close>收起详情</button></div>${memberHtml(e)}<p>下列调用按原生 call_site_id 保存 caller Body、callee 和正常／unwind continuation。聚合到同一函数后仍保留各个调用实例；async 函数调用可能只是创建 Future，不能当成任务已执行完。</p><button id="whole-source">查看完整函数源码</button><div id="source-pane"></div><details><summary>${e.body_keys.length} 个 Body 与原图入口</summary><div class="calls">${e.bodies.map(b=>`<div class="call"><div class="code-path">${esc(b.body_key)}<br>${esc(b.path)} · ${esc(b.role)}</div>${b.root_id?`<a href="./original.html?root=${encodeURIComponent(b.root_id)}">查看此 Root 的原图入口说明 ↗</a>`:'未作为正式 Root 发布；不能伪造入口'}${b.source?`<button data-body-source="${esc(b.body_key)}">看该 Body 源码范围</button>`:''}</div>`).join('')}</div></details><details><summary>${calls.calls.length} 个原生调用点；${calls.resolved} 个 callee 已关联当前实体</summary><div class="calls">${calls.calls.map(c=>`<div class="call"><b>${esc(c.target_name||c.callee.canonical_path||'callee 未进入 Body 索引')}</b><div class="code-path">${esc(c.call_site_id)}</div><span class="tag">${esc(c.classification.scope)}</span><span class="tag">${esc(c.classification.resolution)}</span><span class="tag">${esc(c.target_identity_status||'未补 Definition 身份')}</span><br>${esc(c.source?.source_span?.file)}:${c.source?.source_span?.start_line??'—'}<details><summary>该调用自己的返回绑定</summary><pre>${esc(JSON.stringify(c.continuation,null,2))}</pre></details></div>`).join('')}</div></details>`;
$('whole-source').onclick=()=>source(e.file,e.start,e.end);$('detail').querySelectorAll('[data-body-source]').forEach(b=>b.onclick=()=>{const s=e.bodies.find(x=>x.body_key===b.dataset.bodySource).source;source(s.file,s.span.start_line,s.span.end_line)});bind();$('detail').scrollIntoView({behavior:'smooth',block:'nearest'});}
async function source(file,start,end){let r=await evidenceFetch(`/__source?file=${encodeURIComponent(file)}&start=${start}&end=${end}`);$('source-pane').innerHTML=`<h4>${esc(file)}:${start}–${end}</h4><pre>${esc(await r.text())}</pre>`;}
function edgeDetail(id){const e=flow.edges.find(x=>x.id===id);$('detail').hidden=false;$('detail').className='detail-box';$('detail').innerHTML=`<div class="details-head"><h3>${esc(e.label)}</h3><button data-close>收起详情</button></div><p><b>关系：</b>${esc(kinds[e.kind])}；${esc(e.condition||'局部源码步骤顺序，不宣称跨任务的全局时间顺序')}</p><p>${esc(flow.nodes.find(n=>n.id===e.from).title)} → ${esc(flow.nodes.find(n=>n.id===e.to).title)}</p><p>这条主题边由以下源码锚点支持。函数控制关系页独立显示 MIR 调用点；两种证据没有自动互相冒充。</p>${e.evidence.map(sourceButton).join(' ')}<div id="source-pane"></div>`;bind();$('detail').scrollIntoView({behavior:'smooth',block:'nearest'});}
function questionDetail(id){const q=data.questions.find(q=>q.id===id);$('question-detail').hidden=false;$('question-detail').innerHTML=`<div class="details-head"><h3>${id} · 研究问题与证据边界</h3><button id="close-question">收起</button></div><p>${esc(q.question)}</p><b>必要结论</b><ul>${q.necessary_conclusions.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><b>对应过程</b><p>${q.views.map(v=>`<button data-flow="${v}">${esc(data.flows.find(f=>f.id===v).title)}</button>`).join(' ')}</p><p>已有源码结论：${esc(q.existing_source_status)}；新视图状态：${esc(q.acceptance_status==='source_supported_with_compiler_gaps'?'源码有依据；编译证据仍有缺口':q.acceptance_status)}；真实运行：未验证。</p><p>编译缺口：${esc(q.blocking_gaps.join('；'))}</p><details><summary>${q.anchors.length} 个正式锚点</summary>${q.anchors.map(a=>`<p class="code-path">${esc(a.seq)} · ${esc(a.qualname)} · ${esc(a.file)}:${a.line}</p>`).join('')}</details>${q.analysis.map(doc=>`<p><a href="./analyses/${encodeURIComponent(doc.split('/').pop())}" target="_blank">阅读已有源码分析：${esc(doc)} ↗</a></p>`).join('')}`;$('close-question').onclick=()=>{$('question-detail').hidden=true};bind();$('question-detail').scrollIntoView({behavior:'smooth',block:'nearest'});}
function bind(){document.querySelectorAll('[data-flow]').forEach(b=>b.onclick=()=>chooseFlow(b.dataset.flow));document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>questionDetail(b.dataset.question));document.querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>selectNode(b.dataset.node));document.querySelectorAll('[data-source]').forEach(b=>b.onclick=()=>{const e=data.evidence[b.dataset.source];source(e.file,e.start,e.end)});document.querySelectorAll('[data-function]').forEach(b=>b.onclick=()=>showFunction(b.dataset.function));document.querySelectorAll('[data-edge]').forEach(b=>b.onclick=()=>edgeDetail(b.dataset.edge));document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>{$('detail').hidden=true;selected=null;document.querySelector('.tabs').scrollIntoView({behavior:'smooth'})});}
function chooseFlow(id){flow=data.flows.find(f=>f.id===id);$('flow-select').value=id;$('detail').hidden=true;selected=null;render();document.querySelector('.tabs').scrollIntoView({behavior:'smooth',block:'start'});}
function wires(){const box=document.querySelector('.diagram');if(!box)return;const svg=box.querySelector('svg'),bounds=box.getBoundingClientRect(),rects={};box.querySelectorAll('[data-node]').forEach(n=>{const r=n.getBoundingClientRect();rects[n.dataset.node]={x:r.x-bounds.x,y:r.y-bounds.y,w:r.width,h:r.height}});svg.setAttribute('viewBox',`0 0 ${bounds.width} ${bounds.height}`);let lines='';flow.edges.forEach((e,i)=>{const a=rects[e.from],b=rects[e.to];if(!a||!b)return;let path,lx,ly;const isLoop=e.kind==='loop',same=Math.abs(a.y-b.y)<5;
if(same&&!isLoop&&b.x>a.x&&b.x-a.x-a.w<30){const y=a.y+a.h/2;path=`M ${a.x+a.w} ${y} H ${b.x}`;lx=a.x+a.w+(b.x-a.x-a.w)/2;ly=y-5;}
else if(same&&!isLoop){const sy=a.y+a.h+24;path=`M ${a.x+a.w/2} ${a.y+a.h} V ${sy} H ${b.x+b.w/2} V ${b.y+b.h}`;lx=(a.x+a.w/2+b.x+b.w/2)/2;ly=sy-5;}
else if(b.y>a.y&&!isLoop){const sy=a.y+a.h,ty=b.y,mid=sy+(ty-sy)/2;path=`M ${a.x+a.w/2} ${sy} V ${mid} H ${b.x+b.w/2} V ${ty}`;lx=(a.x+a.w/2+b.x+b.w/2)/2;ly=mid-5;}
else{const rail=8+(i%3)*5;const sy=a.y+a.h+12,ty=b.y-12;path=`M ${a.x+a.w/2} ${a.y+a.h} V ${sy} H ${rail} V ${ty} H ${b.x+b.w/2} V ${b.y}`;lx=a.x+a.w/2+12;ly=sy-4;}
lines+=`<path class="${isLoop?'loop':!['source_sequence','conditional'].includes(e.kind)?'aux':''}" d="${path}"><title>${esc(e.label)}</title></path><text class="edge-label" text-anchor="middle" x="${lx}" y="${ly}">E${i+1}</text>`;});svg.innerHTML=`<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" style="fill:#64748b;stroke:none;marker-end:none"/></marker></defs>`+lines;}
async function render(){const renderedFlowId=flow.id;document.querySelectorAll('[data-view]').forEach(b=>(b.classList.toggle('active',b.dataset.view===view),b.setAttribute('aria-selected',String(b.dataset.view===view))));document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.flow===flow.id));$('title').textContent=flow.title;$('intro').textContent=flow.intro;$('notice').textContent=view==='flow'?'每张卡片是一个源码步骤。箭头编号对应下方关系说明；点步骤可看到功能、源码函数与匹配 Body。':view==='architecture'?'模块边界表示职责与成员归属；下面另列有证据的模块间关系。归属层级不能当成执行先后。':'函数之间只列原生调用点。节点的中文阶段另有源码顺序证据；跨任务消息边在任务流程中单独展示。';
const selectedIds=[...new Set(flow.nodes.flatMap(n=>n.members))];
if(view==='flow'){$('graph').innerHTML=`<div class="diagram"><svg class="wires" aria-label="有源码锚点的步骤连线"></svg><div class="cards">${flow.nodes.map(n=>{let es=entities(n);return `<button class="stage" data-node="${n.id}"><h3>${esc(n.title)}</h3><p>${esc(n.output)}</p><span class="owner">${esc(es.length?es.slice(0,2).map(e=>e.name).join(' / ')+(es.length>2?' ＋'+(es.length-2)+' 个函数':''):'源码锚点 · 身份待匹配')}</span><span class="badge">${n.questions.join(' · ')} · 点开源码与归属</span></button>`}).join('')}</div></div>`;$('connections').innerHTML=`<b>关系与条件（可点击核对）</b><div class="edge-list">${flow.edges.map((e,i)=>`<button data-edge="${e.id}"><span>E${i+1}</span>${esc(e.label)} · ${esc(kinds[e.kind])}</button>`).join('')}</div>`;requestAnimationFrame(wires);}
else if(view==='architecture'){const modules=new Map();selectedIds.forEach(id=>{const e=data.entities[id];if(!modules.has(e.module))modules.set(e.module,[]);modules.get(e.module).push(e)});$('graph').innerHTML=`<div class="modules">${[...modules].map(([m,es])=>`<article class="module"><small>crate ${esc(es[0].crate)} · target ${esc(es[0].target_kind||'未匹配')}</small><h3>${esc(m)}</h3><p>${esc(es[0].role||'职责由当前源码步骤解释')}</p>${es.map(e=>`<button class="fn" data-function="${e.id}">${esc(e.name)} <small>${e.body_keys.length} Body</small></button>`).join('')}</article>`).join('')}</div>`;$('connections').innerHTML=`<h3>模块之间承担的步骤交接</h3><table><tr><th>来源 module</th><th>目标 module</th><th>关系与条件</th></tr>${flow.edges.filter(e=>{const a=flow.nodes.find(n=>n.id===e.from),b=flow.nodes.find(n=>n.id===e.to);return a.members.length&&b.members.length&&data.entities[a.members[0]].module!==data.entities[b.members[0]].module}).map(e=>{const a=entities(flow.nodes.find(n=>n.id===e.from))[0],b=entities(flow.nodes.find(n=>n.id===e.to))[0];return `<tr><td>${esc(a.module)}</td><td>${esc(b.module)}</td><td><button data-edge="${e.id}">${esc(e.label)}</button><br>${esc(kinds[e.kind])}</td></tr>`}).join('')}</table>`;}
else{$('graph').innerHTML=`<details><summary>${selectedIds.length} 个函数的 module、源码和 Body 归属</summary><div class="members">${selectedIds.map(id=>memberHtml(data.entities[id])).join('')}</div></details>`;$('connections').innerHTML='<p>正在读原生调用关系…</p>';let r=await evidenceFetch('/context/relations?entities='+encodeURIComponent(selectedIds.join(','))).then(r=>r.json());if(view!=='functions'||flow.id!==renderedFlowId)return;$('connections').innerHTML=`<h3>这些函数之间的原生调用</h3><p>共 ${r.relations.length} 组关系，保留 ${r.call_count} 个具体调用点。匹配函数不等于 callee Body 也进入了索引。</p><div class="call-graph">${r.relations.map(x=>`<div class="call-relation"><button data-function="${x.from}"><b>${esc(data.entities[x.from].name)}</b><span class="code-path">${esc(data.entities[x.from].module)}</span></button><span class="call-arrow">${x.calls.length} 个调用点<br>⟶</span><button data-function="${x.to}"><b>${esc(data.entities[x.to].name)}</b><span class="code-path">${esc(data.entities[x.to].module)}</span></button></div>`).join('')}</div>${!r.relations.length?'<p>当前场景成员间未匹配到原生直接调用。源码阶段或消息交接仍有证据，不能用归属补造调用边。</p>':''}`;}
$('footer').textContent=`${data.delivery_status}。${data.flows.length} 个过程 · ${data.questions.length} 问已对账 · 基线 ${data.source_commit.slice(0,12)} · 源码职责来自 Step1 与已有 source-analysis。`;bind();}
evidenceFetch('/context/projection.json').then(r=>r.json()).then(d=>{data=d;flow=d.flows[0];$('flow-select').innerHTML=d.flows.map(f=>`<option value="${f.id}">${esc(f.title)}</option>`).join('');$('flow-select').onchange=()=>chooseFlow($('flow-select').value);$('flows').innerHTML=d.flows.map(f=>`<button data-flow="${f.id}">${esc(f.title)}</button>`).join('');$('questions').innerHTML=d.questions.map(q=>`<button data-question="${q.id}">${q.id}</button>`).join('');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;$('detail').hidden=true;render()});window.addEventListener('resize',wires);render();}).catch(e=>{$('notice').textContent='读取证据失败：'+e.message});
